### PR TITLE
Cross check/4

### PR DESCRIPTION
**Pull request by a-reznikov**
1. Task: [link](https://trello.com/c/yfD2VPf8/59-visual-content-fixes)
2. Screenshot:
image

image

3. Deploy: see the Netlify bot section below ↓
4. Done 24.09.2023 / deadline 25.09.2023
5. Score: 

- [x] Improved visual display of content
- [x] The footer is filled with information

### CODE REVIEW

**Review by HellCAT0147 — APPROVED** [review]
Everything is ok!

**Review by LqosL — COMMENTED** [review]
Great job! Isn't it a little too much for a post-prod though?

**Review by LqosL — APPROVED** [review]
Everything looks reasonable

**Comment by a-reznikov** [comment]
> Great job! Isn't it a little too much for a post-prod though?

They're just styles. The functionality was made during.

**Pull request merged**
